'use client';
import { useState } from 'react';
/* import type { Metadata } from 'next'; */
import './globals.scss';
import CustomCursor from '@/components/Cursor';
import CursorProvider from '@/components/Cursor/CursorProvider';
import Socials from '@/components/socials';
import MenuBtn from '@/components/menuBtn/MenuBtn';
import { AnimatePresence } from 'framer-motion';
import Nav from '@/components/nav/Nav';
import NavItem from '@/components/nav/NavItem';
import { navData } from '@/assets/constants/NavData';

import { Inter, Space_Grotesk } from 'next/font/google';

const inter = Inter({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const space_grotesk = Space_Grotesk({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

/* export const metadata: Metadata = {
  title: 'Future vision',
  description: 'Generated by create next app',
};
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [active, setActive] = useState(false);
  return (
    <html lang='en'>
      <body className={`${inter.className} ${space_grotesk.className}`}>
        <MenuBtn active={active} setActive={setActive} />
        <CursorProvider>
          <AnimatePresence mode='wait'>
            {active && (
              <Nav active={active}>
                {navData.map(({ title, path, id }, i) => (
                  <NavItem
                    id={id.toString()}
                    title={title}
                    path={path}
                    key={id}
                    i={i}
                    active={active}
                    setActive={setActive}
                  />
                ))}
              </Nav>
            )}
          </AnimatePresence>
          <CustomCursor />
          <Socials />
          {children}
        </CursorProvider>
      </body>
    </html>
  );
}
